### ISSUE TITLE
extend Host-specific HTTP Accept header to support sub-domains (or globs)

### ISSUE THREAD

**Issue by romain-dartigues** [mjgiarlo/jsonovich#42]
Hi,

it would be nice to have the "Host-specific HTTP Accept header" support sub-domains (as in [@domain](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)) or globs/regexp.

It has been done in [skipCertError](/foudfou/skipCertError/blob/b03f067034c6787312ae4563662f4f7c0965915d/src/chrome/content/overlay.js#L319), but I'm not sure it is _the_ way to do it.

My use-case is to use this functionality on the Intranet or certain sites only (having the same top level), but it could be "to each URI containing `/couchdb/`"...

If it's already working, maybe a little more documentation, because I haven't yet found how to get it working.

Best regards.

**Comment by welwood08** [comment]
In case you're still interested, this will be fully supported in the very near future through [match patterns](https://developer.mozilla.org/Add-ons/WebExtensions/Match_patterns). The infrastructure is already in place in the stored options and code. The next phase of the webextension rewrite will introduce the necessary UI.

**Comment by romain-dartigues** [comment]
Not actively interested at the moment, but I'll be sure to test and give you a feedback the day it'll be available.
Thank you a lot for keeping this feature request alive.
